allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: true
  less: set this to true or false
  sharp: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - less
  - sharp
